"""initial

Revision ID: 001
Revises:
Create Date: 2026-09-21 15:14:13.824799

"""

from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Optional[str] = None
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("language_code", sa.String(), nullable=True),
        sa.Column("native_language", sa.String(length=2), nullable=True),
        sa.Column(
            "english_level",
            sa.Enum(
                "A1", "A2", "B1", "B2", "C1", name="englishlevel", native_enum=False, length=32
            ),
            nullable=True,
        ),
        sa.Column(
            "learning_goal",
            sa.Enum(
                "GENERAL",
                "TRAVEL",
                "BUSINESS",
                "JOB_INTERVIEW",
                "IT",
                "EXAM",
                name="learninggoal",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "communication_format",
            sa.Enum(
                "TEXT", "VOICE", "MIXED", name="communicationformat", native_enum=False, length=32
            ),
            nullable=True,
        ),
        sa.Column("onboarded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "subscription_type",
            sa.Enum("FREE", "PREMIUM", name="subscriptiontype", native_enum=False, length=32),
            server_default="FREE",
            nullable=False,
        ),
        sa.Column("subscription_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_streak", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_study_date", sa.Date(), nullable=True),
        sa.Column("total_study_seconds", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("blocked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("banned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum(
                "GENERAL",
                "TRAVEL",
                "BUSINESS",
                "JOB_INTERVIEW",
                "IT",
                "GRAMMAR",
                "VOCABULARY",
                "ROLE_PLAY",
                name="practicemode",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "scenario",
            sa.Enum(
                "RESTAURANT",
                "HOTEL_CHECK_IN",
                "RECRUITER",
                "WORK_MEETING",
                "CUSTOMER",
                "AIRPORT_SECURITY",
                name="roleplayscenario",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_table(
        "lessons",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "A1", "A2", "B1", "B2", "C1", name="englishlevel", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("content", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lessons_user_id"), "lessons", ["user_id"], unique=False)
    op.create_table(
        "usage_records",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "request_type",
            sa.Enum(
                "CHAT",
                "ASSESSMENT",
                "LESSON",
                "VOCABULARY",
                "SUMMARY",
                "SPEECH_TO_TEXT",
                "TEXT_TO_SPEECH",
                name="requesttype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "estimated_cost", sa.Numeric(precision=12, scale=6), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usage_records_created_at"), "usage_records", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_usage_records_user_id"), "usage_records", ["user_id"], unique=False)
    op.create_table(
        "user_mistakes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("corrected_text", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "GRAMMAR",
                "VOCABULARY",
                "WORD_ORDER",
                "ARTICLES",
                "PREPOSITIONS",
                "VERB_TENSE",
                "SPELLING",
                "STYLE",
                name="mistakecategory",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_mistakes_user_id"), "user_mistakes", ["user_id"], unique=False)
    op.create_table(
        "vocabulary_items",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("phrase", sa.String(), nullable=False),
        sa.Column("translation", sa.String(), nullable=False),
        sa.Column("example", sa.Text(), nullable=True),
        sa.Column("correct_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("incorrect_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "next_review_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "phrase"),
    )
    op.create_index(
        op.f("ix_vocabulary_items_next_review_at"),
        "vocabulary_items",
        ["next_review_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vocabulary_items_user_id"), "vocabulary_items", ["user_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "SYSTEM", "USER", "ASSISTANT", name="messagerole", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_usage", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_vocabulary_items_user_id"), table_name="vocabulary_items")
    op.drop_index(op.f("ix_vocabulary_items_next_review_at"), table_name="vocabulary_items")
    op.drop_table("vocabulary_items")
    op.drop_index(op.f("ix_user_mistakes_user_id"), table_name="user_mistakes")
    op.drop_table("user_mistakes")
    op.drop_index(op.f("ix_usage_records_user_id"), table_name="usage_records")
    op.drop_index(op.f("ix_usage_records_created_at"), table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_index(op.f("ix_lessons_user_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_table("users")
    # ### end Alembic commands ###
