from datetime import timedelta
from typing import Any, Optional, Protocol, Union

from app.application.storage.keys.base import StorageKey


class KvStorage(Protocol):
    async def get[T](self, key: StorageKey[T]) -> Optional[T]: ...

    async def set(
        self,
        key: StorageKey[Any],
        value: Any,
        ex: Optional[Union[int, timedelta]] = None,
    ) -> None: ...

    async def exists(self, key: StorageKey[Any]) -> bool: ...

    async def delete(self, key: StorageKey[Any]) -> None: ...

    async def close(self) -> None: ...

    async def is_webhook_set(self, bot_id: int, webhook_hash: str) -> bool: ...

    async def set_webhook(self, bot_id: int, webhook_hash: str) -> None: ...

    async def clear_webhooks(self, bot_id: int) -> None: ...

    async def is_commands_set(self, bot_id: int, commands_hash: str) -> bool: ...

    async def set_commands_lock(self, bot_id: int, commands_hash: str) -> None: ...
